baseURL = 'https://harikrishna-al.github.io/notes/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'sk3'
contentdir = "content"
layoutdir = "layouts"
builddrafts = "True"
canonifyurls = "False"
publishDir = "docs"
